/**
 * LOCAL_PRODUCTS — 40 financial products with fully consistent attributes.
 * Used as supplementary data alongside API results.
 * All data is internally consistent: low risk ≠ high return, etc.
 */
export const LOCAL_PRODUCTS = [
  // ── SAVINGS ──────────────────────────────────────────────────────────────
  {
    id: "sav-001",
    name: "HBL Premium Savings Account",
    category: "savings",
    description: "High-yield savings account with HBL offering competitive returns and full liquidity. Ideal for emergency funds and short-term goals.",
    expectedReturn: 5.5,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 10000,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },
  {
    id: "sav-002",
    name: "UBL Digital Savings Plan",
    category: "savings",
    description: "UBL's digital savings product with monthly profit payments. No lock-in period, full access to funds anytime.",
    expectedReturn: 6.2,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },
  {
    id: "sav-003",
    name: "Meezan Bank Islamic Savings",
    category: "savings",
    description: "Shariah-compliant profit-sharing savings account. Halal returns based on bank's asset performance.",
    expectedReturn: 5.8,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 1000,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },
  {
    id: "sav-004",
    name: "National Savings Certificate",
    category: "savings",
    description: "Government-backed savings certificate with guaranteed returns. Issued by National Savings Pakistan. Zero default risk.",
    expectedReturn: 7.5,
    riskLevel: "low",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 500,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },
  {
    id: "sav-005",
    name: "Faysal Bank Profit Plus",
    category: "savings",
    description: "Term deposit with higher returns for locking funds for 6-12 months. SECP-regulated, low risk.",
    expectedReturn: 6.8,
    riskLevel: "low",
    liquidity: "moderate",
    timeHorizon: "short",
    minInvestment: 25000,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },
  {
    id: "sav-006",
    name: "Prize Bond (Rs 40,000)",
    category: "savings",
    description: "Government prize bond with quarterly prize draws. Capital fully preserved, with chance of large prize wins.",
    expectedReturn: 4.0,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 40000,
    image: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png",
  },

  // ── INVESTMENT ────────────────────────────────────────────────────────────
  {
    id: "inv-001",
    name: "MCB Arif Habib Equity Fund",
    category: "investment",
    description: "Actively managed equity mutual fund investing in PSX blue-chip stocks. Professionally managed with strong historical performance.",
    expectedReturn: 14.5,
    riskLevel: "high",
    liquidity: "moderate",
    timeHorizon: "long",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-002",
    name: "UBL Stock Advantage Fund",
    category: "investment",
    description: "Diversified PSX equity fund with balanced sector exposure. Suitable for long-term wealth building.",
    expectedReturn: 12.8,
    riskLevel: "high",
    liquidity: "moderate",
    timeHorizon: "long",
    minInvestment: 1000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-003",
    name: "Meezan Islamic Balanced Fund",
    category: "investment",
    description: "Shariah-compliant balanced fund investing in equities and sukuk. Moderate risk with growth and income components.",
    expectedReturn: 9.5,
    riskLevel: "medium",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-004",
    name: "ABL Income Fund",
    category: "investment",
    description: "Fixed income fund investing in government securities and corporate bonds. Steady returns with low-medium risk.",
    expectedReturn: 8.2,
    riskLevel: "medium",
    liquidity: "easy",
    timeHorizon: "medium",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-005",
    name: "HBL Money Market Fund",
    category: "investment",
    description: "Low-risk fund investing in T-bills and short-term instruments. Near-liquid with stable daily NAV.",
    expectedReturn: 7.2,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 500,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-006",
    name: "Atlas Stock Market Fund",
    category: "investment",
    description: "Large-cap equity fund focusing on KSE-100 top performers. Long-term capital appreciation objective.",
    expectedReturn: 16.0,
    riskLevel: "high",
    liquidity: "moderate",
    timeHorizon: "long",
    minInvestment: 10000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-007",
    name: "NAFA Pakistan Income Fund",
    category: "investment",
    description: "Conservative income fund with exposure to PIBs and T-bills. Suitable for risk-averse investors seeking regular income.",
    expectedReturn: 7.8,
    riskLevel: "low",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-008",
    name: "Faysal Islamic Equity Fund",
    category: "investment",
    description: "Halal equity fund investing in Shariah-screened PSX companies. Growth-focused with long investment horizon.",
    expectedReturn: 13.2,
    riskLevel: "high",
    liquidity: "moderate",
    timeHorizon: "long",
    minInvestment: 1000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-009",
    name: "JS Growth Fund",
    category: "investment",
    description: "Aggressive growth fund with diversified equity portfolio. Targets above-market returns over a 5+ year horizon.",
    expectedReturn: 17.5,
    riskLevel: "high",
    liquidity: "moderate",
    timeHorizon: "long",
    minInvestment: 10000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "inv-010",
    name: "Alfalah GHP Alpha Fund",
    category: "investment",
    description: "Multi-asset fund combining equities, income, and money market instruments for balanced risk-return.",
    expectedReturn: 10.4,
    riskLevel: "medium",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },

  // ── INSURANCE ─────────────────────────────────────────────────────────────
  {
    id: "ins-001",
    name: "Jubilee Life Endowment Plan",
    category: "insurance",
    description: "Whole-life insurance with savings component. Provides death benefit plus maturity payout. Lock-in but secure.",
    expectedReturn: 6.5,
    riskLevel: "low",
    liquidity: "locked",
    timeHorizon: "long",
    minInvestment: 12000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },
  {
    id: "ins-002",
    name: "EFU Life Investment Plan",
    category: "insurance",
    description: "Unit-linked insurance plan where premiums are invested in equity funds. Higher returns with insurance cover.",
    expectedReturn: 9.8,
    riskLevel: "medium",
    liquidity: "locked",
    timeHorizon: "long",
    minInvestment: 24000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },
  {
    id: "ins-003",
    name: "State Life Whole Life Policy",
    category: "insurance",
    description: "Government-backed whole life insurance. Guaranteed sum assured with bonus additions. Extremely low risk.",
    expectedReturn: 5.2,
    riskLevel: "low",
    liquidity: "locked",
    timeHorizon: "long",
    minInvestment: 6000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },
  {
    id: "ins-004",
    name: "Adamjee Family Takaful",
    category: "insurance",
    description: "Shariah-compliant family takaful plan. Provides mutual risk coverage with surplus sharing mechanism.",
    expectedReturn: 6.0,
    riskLevel: "low",
    liquidity: "locked",
    timeHorizon: "long",
    minInvestment: 15000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },
  {
    id: "ins-005",
    name: "Jubilee Health Shield Plus",
    category: "insurance",
    description: "Comprehensive health insurance with investment component. Covers hospitalization plus builds cash value.",
    expectedReturn: 5.8,
    riskLevel: "low",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 20000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },
  {
    id: "ins-006",
    name: "TPL Life Retirement Plan",
    category: "insurance",
    description: "Pension-linked insurance plan accumulating retirement corpus over 20+ years. Tax benefits available.",
    expectedReturn: 7.2,
    riskLevel: "low",
    liquidity: "locked",
    timeHorizon: "long",
    minInvestment: 36000,
    image: "https://cdn-icons-png.flaticon.com/512/3163/3163053.png",
  },

  // ── CRYPTO ────────────────────────────────────────────────────────────────
  {
    id: "cry-001",
    name: "Bitcoin (BTC) Investment",
    category: "crypto",
    description: "Direct investment in Bitcoin, the world's largest cryptocurrency by market cap. High volatility, high potential returns.",
    expectedReturn: 24.0,
    riskLevel: "high",
    liquidity: "easy",
    timeHorizon: "long",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/5968/5968260.png",
  },
  {
    id: "cry-002",
    name: "Ethereum (ETH) Fund",
    category: "crypto",
    description: "Ethereum investment via regulated crypto fund. Benefits from DeFi and smart contract ecosystem growth.",
    expectedReturn: 20.5,
    riskLevel: "high",
    liquidity: "easy",
    timeHorizon: "long",
    minInvestment: 3000,
    image: "https://cdn-icons-png.flaticon.com/512/2991/2991367.png",
  },
  {
    id: "cry-003",
    name: "Crypto Basket Fund",
    category: "crypto",
    description: "Diversified basket of top 10 cryptocurrencies. Reduces single-asset risk while maintaining high growth potential.",
    expectedReturn: 18.0,
    riskLevel: "high",
    liquidity: "easy",
    timeHorizon: "long",
    minInvestment: 10000,
    image: "https://cdn-icons-png.flaticon.com/512/2991/2991367.png",
  },
  {
    id: "cry-004",
    name: "Binance Coin (BNB) Plan",
    category: "crypto",
    description: "Investment in BNB token with staking rewards. Active use case in Binance ecosystem reduces volatility somewhat.",
    expectedReturn: 15.5,
    riskLevel: "high",
    liquidity: "easy",
    timeHorizon: "medium",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2991/2991367.png",
  },
  {
    id: "cry-005",
    name: "Stable Yield Crypto Fund",
    category: "crypto",
    description: "USDT-based stablecoin lending fund. Earns yield through DeFi protocols with significantly lower crypto volatility.",
    expectedReturn: 12.0,
    riskLevel: "medium",
    liquidity: "moderate",
    timeHorizon: "short",
    minInvestment: 5000,
    image: "https://cdn-icons-png.flaticon.com/512/2991/2991367.png",
  },
  {
    id: "cry-006",
    name: "Solana (SOL) Growth Plan",
    category: "crypto",
    description: "High-performance blockchain investment. Solana's speed and low fees drive adoption in NFTs and DeFi.",
    expectedReturn: 22.0,
    riskLevel: "high",
    liquidity: "easy",
    timeHorizon: "long",
    minInvestment: 7000,
    image: "https://cdn-icons-png.flaticon.com/512/2991/2991367.png",
  },

  // ── BONDS (bonus category) ────────────────────────────────────────────────
  {
    id: "bnd-001",
    name: "Pakistan Investment Bond (5-Year)",
    category: "investment",
    description: "5-year government bond with semi-annual coupon payments. Zero default risk, backed by Government of Pakistan.",
    expectedReturn: 8.5,
    riskLevel: "low",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 100000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "bnd-002",
    name: "Corporate Sukuk — K-Electric",
    category: "investment",
    description: "Shariah-compliant corporate bond issued by K-Electric. Fixed profit rate with maturity in 3 years.",
    expectedReturn: 9.2,
    riskLevel: "medium",
    liquidity: "moderate",
    timeHorizon: "medium",
    minInvestment: 50000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
  {
    id: "bnd-003",
    name: "Treasury Bills (91-Day)",
    category: "investment",
    description: "Short-term government T-bills with 3-month maturity. Highly liquid, risk-free, and ideal for parking surplus funds.",
    expectedReturn: 6.9,
    riskLevel: "low",
    liquidity: "easy",
    timeHorizon: "short",
    minInvestment: 100000,
    image: "https://cdn-icons-png.flaticon.com/512/2920/2920277.png",
  },
];
